name: flutter_app_template
description: This project is "flutter app template" from abrt2322
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.5
  google_fonts: ^2.3.1
  fimber: ^0.6.5
  enum_to_string: ^2.0.1
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.2
  flutter_gen_runner: ^4.1.6

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/